# Generated by Django 6.0.2 on 2026-02-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FRIEND_REQUEST', 'Friend Request'), ('TOURNAMENT_REQUEST', 'Tournament Join Request'), ('INVITATION', 'Tournament Invitation'), ('MATCH_RESULT', 'Match Result')], max_length=20)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
