# Generated by Django 6.0.2 on 2026-02-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('goal_difference', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-points', '-goal_difference', '-goals_for'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(choices=[('LEAGUE', 'League'), ('R16', 'Round of 16'), ('QF', 'Quarter Final'), ('SF', 'Semi Final'), ('FINAL', 'Final')], default='LEAGUE', max_length=10)),
                ('score_player1', models.IntegerField(default=0)),
                ('score_player2', models.IntegerField(default=0)),
                ('decided_by', models.CharField(choices=[('NORMAL', 'Normal Time'), ('EXTRA_TIME', 'Extra Time'), ('PENALTIES', 'Penalties')], default='NORMAL', max_length=15)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PLAYED', 'Played'), ('LOCKED', 'Locked')], default='SCHEDULED', max_length=10)),
                ('played_at', models.DateTimeField(blank=True, null=True)),
                ('source_score', models.CharField(choices=[('MANUAL', 'Manual'), ('AI', 'AI Agent')], default='MANUAL', max_length=10)),
            ],
        ),
    ]
